[package]
name = "cw-ibc-lite-shared"
description = "Shared package for IBC Lite in CosmWasm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ibc-core-host = { workspace = true }
ibc-client-cw = { workspace = true }
cw-ownable = { workspace = true }
sha2 = { workspace = true }
ibc-proto = { workspace = true }
derive_more = { workspace = true }
cw-ibc-lite-derive = { workspace = true }
